# Enable color logging
defaults:
  - override hydra_logging: default
  - override job_logging: default

# To allow hydra to change the current working directory when running the file
job:
  chdir: True

# Interpolated variables output directory, generated dynamically on each run
run:
  dir: ${full_path}

# This makes hydra overwrite the logging instead of appending
job_logging:
  handlers:
    file:
      mode: w
